--- 
before_script: "cd $TRAVIS_BUILD_DIR"
cache: 
  directories: 
    - /tmp/texlive
    - $HOME/.texlive
dist: bionic
install: 
  - "source ./texlive/texlive_install.sh"
language: generic
script: 
  - "texliveonfly Main.tex"
  - "lualatex Main.tex"
